<a href="https://colab.research.google.com/github/Ragib301/Sentiment-Analysis-BERT-on-Yelp-Reviews/blob/main/Sentiment_Analysis_with_BERT_Neural_Network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Install and Import Dependencies

In [ ]:
!pip install -q torch torchaudio torchvision torchtext torchdata
!pip install -q transformers requests beautifulsoup4 pandas numpy deep-translator
print(f"Setup Completed!")

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 4.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 38.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 29.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 16.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 840.2 kB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 5.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 11.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 7.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 6.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 78.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 63.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.0/62.0 kB 4.1 MB/s eta 0:00:00
Setup Completed!

In [ ]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch
import requests
from bs4 import BeautifulSoup
from deep_translator import GoogleTranslator
import re

# 2. Instantiate Model

In [ ]:
tokenizer = AutoTokenizer.from_pretrained('nlptown/bert-base-multilingual-uncased-sentiment')
model = AutoModelForSequenceClassification.from_pretrained('nlptown/bert-base-multilingual-uncased-sentiment')

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/39.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/953 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/872k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/669M [00:00<?, ?B/s]

# 3. Encode & Calculate Sentiment

In [ ]:
tokens = tokenizer.encode('Ahh, It was good but could have done better!', return_tensors='pt')

In [ ]:
result = model(tokens)
result

SequenceClassifierOutput(loss=None, logits=tensor([[-1.3351,  0.6217,  2.0665,  0.6396, -1.7678]],
       grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)

In [ ]:
rating = int(torch.argmax(result.logits))+1
rating

3

# 4. Collect Reviews

In [ ]:
regex = re.compile(r'^\s+|\s+$')

def clean_text(text):
  if re.search(r'[\u0980-\u09FF]+', text):
    return GoogleTranslator(source='bn', target='en').translate(text)
  else:
    return re.sub(regex, '', text)

In [ ]:
r = requests.get(
    "https://store.roboticsbd.com/development-boards/94-8-arduino-uno-r3-robotics-bangladesh.html")
soup = BeautifulSoup(r.text, 'html.parser')
content = soup.find_all("div", class_="col-md-12 content-block")
reviews = [clean_text(result.text) for result in content]
print(reviews)

['quality was very nice', 'Good', 'good', 'Good', 'Worked', 'Excellent', '.', 'Very good product', 'The product is original and works fine and is in pristine condition', 'good', 'Good product.', 'Good', 'I did not get the USB programming cable which was supposed to be included in the parcel', 'Good', 'good quality', 'Good quality', "The product works fine just as intended.Though the back side could look better but it\\'s ignorable.", 'Good', 'excellent product', 'Nice', 'Good', 'Good', 'Good', 'Good product', 'Products is good.', 'I am so happy to buy the product from Robotics BD.com because they have been able to deliver the product in a very quick time and their product is quite low than other companies.', 'good', 'Good Component', 'I brought it from their office . every product was intact , fresh , similar to the picture given on the RoboticsBD website. I have not used it yet not but I will update here.', 'Product is very good quality', 'Good Product', 'Good', 'Little bit of overpriced', 'Excellent', 'All in separate packets, cables were included.', 'works well', 'Ok', '..', '.', 'Good', 'Good', 'product ok', 'Good condition', 'Best products and also value for Money', 'Work sGreat', 'Satisfied', 'Real product', 'Excellent', 'Grear', 'Ok for sure and working', 'Good', 'Good', 'Genuine product', 'Good', 'Good', 'Bought this items for my son. It worked perfectly', 'Good quality', 'Indeed a quality uno', 'ok', 'working fine', 'Price is too high compared market price.', 'Thanks product as expected', 'super', 'Good', 'Worked', 'The product is good.', 'that’s good any one can buy this product.', 'good', 'good', 'Good', 'Good', 'GOOD', 'Great', "Genuine Product, Only Suggestions I want to add is to make the cable a little longer. It\\'s so short.", 'Original product', 'good', 'The roduct quality is good', 'Nicely working', 'Good', 'The product is very good', 'its a good product.', 'Good though.', 'Nice', 'I found the item as good as I want.', 'Well product', 'one of my favourate things', 'Good product. Satisfied', 'This product in very nice. I am using it with no problem.', 'Quality full', 'good', 'Awesome', 'I am giving reviews for some time using the product. Very sustainable and good quality I like.', 'Great Product', 'Best product. Very fast service. Thanks to roboticsbd.', 'Good', 'Jsjs', 'Product quality good. No problem. Got 50 tk discount.', 'Good', 'Very good', 'Products are great and also service', 'Good', 'Satisfying', 'Nice', 'Functional product', 'Good working', 'I received the product with good condition. Thanks RoboticsBD', 'The product was good. The product fulfilled the requirement.', 'Good quality', 'Working pretty good', 'Very good product.', 'good', 'Good', 'Very useful and fun', '.', 'I am very happy to buy this.\\r\\nWorks fine', 'Good', 'Great product', 'Good', 'Thanks Robotics BD for delivering all the products in good conditions', 'Good', 'Very good product.', 'Okay', '100% okay and perfectly packed', 'functions perfectly', 'There was no problem..', '10', 'This is good.', 'Good product.', 'Cable wasn’t good', 'tires pretty good', 'Good condition and work perfectly.', 'Its a must needed product with a fare price. I bought one too and its giving a good service but its not italian .Rather , I think Its from China', 'Good products and allays good services', 'Works great.', 'Nice product', 'Good', 'Got what I expected. Works nicely. Recommended for any electrical parts and products.', 'The product was well packed.', 'good', 'The product was well packed. Working good.', 'fully satisfied with this product', 'Valo', 'Good', 'excellent', 'Made in Italy was a good deal at this price.', 'Nice products', 'I purchased 2 servo motor. Excellent product', 'Good', 'Nice and genuine product. Working fine', 'That was awesome', "It is working properly.\\r\\nAnd I\\'m using in my project.", 'Works great.', 'superrr', 'Good. Everyone can go for it.', 'your product is very nice and we are always with you\\r\\n', 'Ok', 'Liked the packaging.', 'A fantastic machine', 'The quality of the product is good.', 'Great product', 'Quality of the product is so good. Their service is fast and their behaviour is charming as well.', "That\\'s a good product", 'It was good', 'You can use easily.', 'Good', 'Good', 'Useful', 'Motamuti valo', 'Good', 'Good', 'Great product wish the cable that came with it was longer', 'Very good condition', 'Worth purchasing and thanks to roboticsbd', 'Ok', 'A', 'great product with fabulous efficiency.', 'Good product, their service is very good.', 'perfectly working', 'Wow', 'Good Product', 'Everything Okay. Works good.', 'ok', 'Great', 'I am fully satisfied. I got better service from you than I did. Your delivery service is actually very good within 2 days, and all the products are perfect. Damn for delayed reviews. After completing the project that I bought the products for it, it was a little late to give the review.', 'original product', 'H', 'Original product', 'Reasonable price and great communication', 'really pleased with the product and enjoying myself by making new projects with the help of this uno.', 'Works totally fine. No problems at all', 'awesome tools', 'It was able to carry out simple sketches.', 'Very satisfied with this product. It was in good shape and packaged well.', 'Very Good Product...', 'very good', 'Best', "Hello everyone, how are you\\r\\nI\\'m very happy to purchase usb sheild from here. Becoz i try to find where i buy this product but when i search on google then i found this site & oder instantly... Now my program working fine...\\r\\nThanks\\r\\n to roboticsbd", 'Alhamdulliah jamon ta chayesi tamon ta paychi', 'best', 'Very good', 'Product was good, packaging satisfactory.', 'nicely works', 'Very good product', 'premium product and great service. Go ahead roboticsbd', 'Very Good quality ,  good price', "It\\'s run perfect", 'Product is good. And obviously delivery on time.', 'Intake pack', 'Very good', 'Highly recommended for begainners.', 'Good quality product', 'good', 'Well', 'Ok', 'Good quality', 'Good', 'good quality', 'Good', 'Good', "hmm...it\\'s really good...you should try it!!!", 'found arduino in good condition and well packaged', 'Very good product.', 'Good condition and packaging are also good. \\r\\nI have tested this Product. The quality of the product I received is very good. I recommended.', 'Good', 'Good quality for the price.', 'Great one', 'Satisfied', "It\\'s quite good", 'It is a very good product in a reasonable price.', 'Great product......quick delivery', 'I have got all the products very fast and well - packed.', 'Very Good Product Thanks', 'Nice', 'Nice product', 'Very good product.', 'ok', 'Bad Ekta Company is giving Ekta Arduino \\ r \\ n photos one \\ r \\ n is giving another \\ r \\ n to the other', 'Good', 'Original', 'Quality product', 'Good', 'Components are operational.', 'ok', 'Good product', 'works fine', 'Valo chilo onk', 'great', 'Nice', 'Good', 'Quite good.', 'good', 'Good', 'Good', 'Good', 'Intact and working fine. Thanks\\r\\n', 'just as good as i expected', 'Good', 'Best', 'work well', 'Nice product', 'The arduino was very good', 'Very Good', 'Best quality', 'Ok', 'work Properly', 'Works great. No fault.', 'Good', 'Very Well', 'Robotics  Bd is one of the best online electronics shop.  The product and its service is great and this shop reach product to door faster than any other online shop', 'Best', 'Arduino was in good condition and I was afraid of burning my arduino. But It worked well', 'Every part was good. Thanks Robotics BD. And this Arduino UNO is doing well.', 'Good', 'Product is amazing. Trusted online shop for coming engineerings. Great. Thank you for your fast service. Hope you always keep it up', 'It really works. Good efficiency.', 'I get the product', 'That was good, I am glad to have this', 'Good', 'working good', "Is it  without the cable ?\\r\\nI didn\\'t get it ..", 'Very Good', 'good product', 'It came exactly as described', 'Exactly same', 'Asome product and great performance', 'Asome product', 'good product and within 24 hour delivery in chittagong. But need to update customer service. customer service response to late', 'Get the product, quality is good.', 'Good', 'Good', 'Ok', 'Great product. I am satisfied.', 'the product in well enough and works well', 'The board is functioning as expected.', "Got the product. Still haven\\'t used it yet. review it after using", 'Good', 'best product', 'Good', 'Good packaging and authentic product, received in expected delivery time. Thanks RoboticsBD.', 'Great', 'Working great!', 'I got that as I ordered', 'Good product, works like a charm!', 'Satisfied', 'Best', 'Amazing performance', 'gd', "Robotics BD just smashed all My confusion's and Suspicious thoughts about their service through an Unbelievable delivery time and Product quality. After unpacking the well packed content, my expression was OOOOOOOOOOOooooooooooohhhhhhhhhhhh...........................  Love you Robotics.", "Robotics BD just smashed all My confusion's and Suspicious thoughts about their service through an Unbelievable delivery time and Product quality. After unpacking the well packed content, my expression was OOOOOOOOOOOooooooooooohhhhhhhhhhhh...........................  Love you Robotics.", "Robotics BD just smashed all My confusion's and Suspicious thoughts about their service through an Unbelievable delivery time and Product quality. After unpacking the well packed content, my expression was OOOOOOOOOOOooooooooooohhhhhhhhhhhh...........................  Love you Robotics.", 'nicenicenice', 'gd', 'the product is really good. Works like a charm', 'Satisfied', 'Working very much well', 'Actual perfect product at good price', '.', 'good', 'Recommend', 'Satisfied', 'Works fine!', 'Works its fine', 'Good', 'GREAT!!!!!!!! Too good at a reasonable price.....', 'The quality was really good... And the price was low compared to others...', 'Products were expected and completely satisfied', 'Very good in performance', 'valo', 'Good', 'satisfied', 'this product was in well condition and working fine.', 'It works perfectly', 'Great', 'nice product, perfectly worked without any problem. Alhamdulillah.', 'Work as expected', 'satisfied', 'Great Product', 'Working fine.', 'Best products', 'Good', 'Got actual device', 'It was in good condition. Nice packaging', 'The product quality was good. I am satisfied with this product.', 'five star', 'The product is good.', 'This chip makes my codes live. I live this thing. And also service from RoboticsBD is great! They sent my products in time.', 'This module makes my codes alive! I love it!', 'Excellent', 'everything is good', 'they have qualited products', 'got my product in time.', 'yeah its great !  your service is good because of i got this my needed time ! thanks you for providing .........this component but paribahan fee is very high so need to decrease !!!', "alert('test')", 'A very good one. Price is fine. East to install and use.', 'So far so good!', 'Good Product']

In [ ]:
reviews[8]

'The product is original and works fine and is in pristine condition'

# 5. Load Reviews into DataFrame and Score

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.DataFrame(np.array(reviews), columns=['Reviews'])
df.head()

                 Reviews
0  quality was very nice
1                   Good
2                   good
3                   Good
4                 Worked

In [ ]:
def sentiment_score(review):
  tokens = tokenizer.encode(review, return_tensors='pt')
  result = model(tokens)
  return int(torch.argmax(result.logits))+1

In [ ]:
num = 30
print(df['Reviews'].iloc[num])
sentiment_score(df['Reviews'].iloc[num])

Good Product

4

In [ ]:
df['Sentiment'] = df['Reviews'].apply(lambda x: sentiment_score(x[:512]))
df

                                               Reviews  Sentiment
0                                quality was very nice          5
1                                                 Good          4
2                                                 good          4
3                                                 Good          4
4                                               Worked          4
..                                                 ...        ...
351  yeah its great !  your service is good because...          4
352                                      alert('test')          4
353  A very good one. Price is fine. East to instal...          4
354                                    So far so good!          5
355                                       Good Product          4

[356 rows x 2 columns]